### ISSUE TITLE
Missing GitHub CI to automate the checking of the code

### ISSUE THREAD

**Issue by pythonbrad** [Mindful/eei#15]
### Description
A GitHub action can help us to verify that:
- the code formatting is ok
- the good practices are respected
- the build is ok

**Comment by pythonbrad** [comment]
@Mindful, what do you think about add a GitHub action to automate the checking of the code?
A GitHub action, can also be used to automate the release of the compiled package.

**Comment by Mindful** [comment]
If you want to do this, I am open to it. That said, I think that in general GitHub actions to verify code formatting/build/etc. are most useful on projects that have a lot of contributors. Right now this is still a pretty small project without a lot of activity, so I think a CI might be overkill here.

That said, there's no harm, so if you want to open a PR I'm open to it. That said I think my inclination would be to say that in my mind: 
[upgrading rust version ](https://github.com/Mindful/eei/issues/14) > new features > CI
